Latest version of Thomas Lockney's sbt shell script

diff --git a/bin/sbt b/bin/sbt
--- a/bin/sbt
+++ b/bin/sbt
@@ -1,6 +1,6 @@
-#!/bin/sh
+#!/bin/sh -e
 
-if [ ! $SBT_VERSION ]; then SBT_VERSION=0.7.1; fi
+if [ ! $SBT_VERSION ]; then SBT_VERSION=0.7.4; fi
 if [ ! $SBT_DIR ]; then SBT_DIR=$HOME/.sbt; fi
 if [ ! $SBT_FILENAME ]; then SBT_FILENAME=sbt-launch-$SBT_VERSION.jar; fi
 if [ ! $SBT_LOCATION ]; then SBT_LOCATION=$SBT_DIR/$SBT_FILENAME; fi
@@ -12,13 +12,18 @@ then
 	echo "Could not find $SBT_FILENAME in $SBT_DIR, downloading..."
 	mkdir -p $SBT_DIR
 	if which wget > /dev/null; then
-		wget --progress=bar "$SBT_URL" -O $SBT_LOCATION
+		CMD="wget --progress=bar $SBT_URL -O $SBT_LOCATION"
 	elif which curl > /dev/null; then
-		(cd $SBT_DIR; curl "$SBT_URL" -o $SBT_LOCATION)
+		CMD="curl $SBT_URL -o $SBT_LOCATION"
 	else
 		echo "Could not find wget or curl."
 		exit 1
 	fi
+   if ! $CMD; then
+      echo "Failed retrieving $SBT_URL ... cleaning up."
+      if [ -f $SBT_LOCATION ]; then rm -r $SBT_LOCATION; fi
+      exit 1
+   fi
 fi
 
-java -jar $SBT_LOCATION "$@"
+java $SBT_OPTS -jar $SBT_LOCATION "$@"
